### ISSUE TITLE
Issue running in docker

### ISSUE THREAD

**Issue by paulbdavis** [Sorunome/mx-puppet-bridge#18]
On current master, building the docker container results in this message:

```
Error: Cannot find module '/opt/mx-puppet-discord/node_modules/mx-puppet-bridge/node_modules/matrix-bot-sdk/lib/index.js'. Please verify that the package.json has a valid "main" entry
```

**Comment by Sorunome** [comment]
Someone on mx-puppet-bridge made a PR to fix that issue, merged it literally just now. Does that also work for you?

**Comment by paulbdavis** [comment]
I accidentally reported this against this repo instead of the discord one, but I guess that's for the best. I'll try updating the dep and trying again

**Comment by paulbdavis** [comment]
I'm now getting errors about not being able to find `mx-puppet-bridge` during the build step 

```
src/db/schema/v1.ts(1,34): error TS2307: Cannot find module 'mx-puppet-bridge'.
```

(this is using the discord bridge that imports this library)

`"mx-puppet-bridge": "git+https://github.com/Sorunome/mx-puppet-bridge.git#master",` <- this is what I changed the dep to

**Comment by Sorunome** [comment]
> "mx-puppet-bridge": "git+https://github.com/Sorunome/mx-puppet-bridge.git#master", <- this is what I changed the dep to

This won't work as you'd need to manually cd into the node_modules dependency and tsc it, then.

Did you try the newest discord build? Soru literally merged a PR that supposively fixes that issue right after she saw you opened this issue

**Comment by paulbdavis** [comment]
That seems to have fixes the issues I was having, thanks!
