### ISSUE TITLE
Support shared secret for automatic double puppeting

### ISSUE THREAD

**Issue by paulbdavis** [Sorunome/mx-puppet-bridge#19]
It would be nice to be able to specify a [shared secret](https://github.com/devture/matrix-synapse-shared-secret-auth) to the mx-puppet-* bridges so that it can set up the double puppeting automatically rather than having to find and send the matrix token.

**Comment by Sorunome** [comment]
That feature already exists https://github.com/Sorunome/mx-puppet-bridge#automatic-double-puppeting
