### ISSUE TITLE
[Feature request] Port Skype bridge to mx-puppet-bridge backend

### ISSUE THREAD

**Issue by MurzNN** [Sorunome/mx-puppet-bridge#28]
Skype is very popular messenger and it already have bridge to Matrix, based on matrix-puppet-bridge library: https://github.com/matrix-hacks/matrix-puppet-skype
But it miss multi-user support, so will be good to port it into mx-puppet-bridge backend.

**Comment by Sorunome** [comment]
If anyone is willing to pick this up (or any other third party protocol bridging), soru'd be very happy to help.

Currently sorus main focus is (apart from university) on the main library to add in all the features she wanted to have

**Comment by MurzNN** [comment]
Seems it happens here https://github.com/Sorunome/mx-puppet-skype - great thanks!
