### ISSUE TITLE
Feature request: forward logged errors to specific mxid

### ISSUE THREAD

**Issue by matejdro** [Sorunome/mx-puppet-bridge#35]
Currently, if anything goes wrong with the bridge, error is printed into logs. Unless I'm checking logs regularly, it can be missed easily. If that error causes bridged messages to not be forwarded either way without any indication that things are not okay, it can create pretty annoying problem.

So what if admin of the bridge could set up specific mxid in bridge's config that would receive any error messages via Matrix? It wouldn't even need to be transcript of the error, just a notification "hey, something has gone wrong. Check the logs."

**Comment by Sorunome** [comment]
Good idea. How does it sound to configure a room id (the internal thingy starting with `!`) for logging?

**Comment by matejdro** [comment]
I'm not that versed in Matrix. Does that mean that I would have to create a room in Riot and then paste the ID into config? That is fine by me.

**Comment by Sorunome** [comment]
After thinking more about this, this is not something soru will implement. It comes with too many hassles of logging triggering logging etc.

You can always log to a file. If you want, you could write a bot that reads that file and sends the contents wherever. Sorry about that.

**Comment by matejdro** [comment]
That's fair. I guess it is a kick in the butt for me to set up some proper logging system on my setup :-) .
