### ISSUE TITLE
Double puppet token not renewed on failure

### ISSUE THREAD

**Issue by flukiluke** [Sorunome/mx-puppet-bridge#37]
If an attempt to puppet the user on the Matrix side fails, the bridge should try to re-login with the shared secret method if possible. This allows recovering from the user changing their password, or just removing the bridge's session.

The required changes are presumably in UserSynchroniser.getClientFromTokenCallback() to handle the homeserver returning an M_UNKNOWN_TOKEN error.

**Comment by Sorunome** [comment]
Should be fixed in https://github.com/Sorunome/mx-puppet-bridge/commit/308acb31ae11f03a305aaa28883408ec3af61305
