### ISSUE TITLE
Reuse room if room alias already exists

### ISSUE THREAD

**Issue by Cadair** [Sorunome/mx-puppet-bridge#53]
I have got stuck in a situation where on receiving a message (from slack) I get an error in the logs `{ errcode: 'M_ROOM_IN_USE', error: 'Room alias already taken' }`.

It would be good if the bridge on seeing this error tried to reuse the room with that alias rather than silently dropping messages on the floor.

**Comment by Sorunome** [comment]
Implemented in https://github.com/Sorunome/mx-puppet-bridge/commit/747574b354f439ad3b596c864704d9f9efb3522e
