### ISSUE TITLE
Bridge

### ISSUE THREAD

**Issue by mentalisit** [Sorunome/mx-puppet-bridge#75]
how to bridge multiple discord channels

**Comment by jdreichmann** [comment]
After logging in using the bridge bot, use `listrooms $puppetId` aand `bridgechannel $puppetId $channelId` to bridge multiple channels. THhe $channelId is listed in the `listrooms` output.

**Comment by mentalisit** [comment]
can you show a sample

**Comment by mentalisit** [comment]
> After logging in using the bridge bot, use `listrooms $puppetId` aand `bridgechannel $puppetId $channelId` to bridge multiple channels. THhe $channelId is listed in the `listrooms` output.

can you show a sample

**Comment by Sorunome** [comment]
please read the available documentation https://github.com/matrix-discord/mx-puppet-discord

**Comment by mentalisit** [comment]
> пожалуйста, прочтите доступную документацию https://github.com/matrix-discord/mx-puppet-discord

@Sorunome 
posts are coming to the matrix, but I need them to go to another Discord channel
