### ISSUE TITLE
Update better-sqlite3

### ISSUE THREAD

**Issue by baltitenger** [Sorunome/mx-puppet-bridge#79]
Currently, the project depends on version `6.0.1` of `better-sqlite3`, which fails to build on my system. However, seemingly no change is required to target the latest version (`7.1.5`), which I'm able to build. (I might be wrong, but `npm test` completed without errors when building with that version.)

**Comment by auscompgeek** [comment]
Looks like multiple people are seeing better-sqlite3@6 fail to build with node v16.3.0. It looks like better-sqlite3@7 builds fine on node 16 though.
