### ISSUE TITLE
listusers results in M_TOO_LARGE

### ISSUE THREAD

**Issue by twouters** [Sorunome/mx-puppet-bridge#8]
My slack instance has ~800 users and listusers fails with the following

```
Sep-24 10:28:10.408 [bot-sdk-MatrixLiteClient] error: (REQ-6) { errcode: 'M_TOO_LARGE', error: 'event too large' }
```

The bot messages should probably be split up in multiple events once it exceeds the event size limit.

**Comment by Cadair** [comment]
I also ran into this

**Comment by twouters** [comment]
fyi https://matrix.org/docs/spec/client_server/latest#size-limits
